config/routes.rb
Rails.application.routes.draw do
  resources :stations
  resources :properties
  
  root 'properties#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
    validates :name, presence: true
    validates :rent_fee, presence: true
    validates :address, presence: true
    validates :build_year, presence: true
    validates :remark, presence: true

    has_many :stations, dependent: :destroy
    accepts_nested_attributes_for :stations, reject_if: :all_blank, allow_destroy: true
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :property
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  def index
    @properties = Property.all
  end

  def show
  end

  def new
    @property = Property.new
    @property.stations.build
  end

  def edit
  end

  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:name, :rent_fee, :address, :build_year, :remark, stations_attributes: [:id, :no, :name, :railway_name, :min_to_walk])
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:no, :name, :railway_name, :min_to_walk, :property_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def link_to_add_fields(name, f, association)
        new_object = f.object.send(association).klass.new
        id = new_object.object_id
        fields = f.fields_for(association, new_object, child_index: id) do |builder|
            render(association.to_s.singularize + "_fields", s: builder)
        end

        link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rental Properties</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_for @property do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :rent_fee %>
    <%= form.number_field :rent_fee %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :build_year %>
    <%= form.number_field :build_year %>
  </div>

  <div class="field">
    <%= form.label :remark %>
    <%= form.text_area :remark %>
  </div>

  <div class="field">
    <p><b>Station Near</b></p>
    <%= form.fields_for :stations do |s| %>
      <%= render 'station_fields', s: s %>
    <% end %>
    <p>
    <%= link_to_add_fields "Add Station", form, :stations %>
    </p>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
  $('form').on('click', '.remove_fields', function(e) {
    $(this).prev('input[type=hidden]').val('1');
    $(this).closest('div').hide();
    return e.preventDefault();
  })

  $('form').on('click', '.add_fields', function(e) {
    var regexp, time;
    time = new Date().getTime();
    regexp = new RegExp($(this).data('id'), 'g');

    $(this).before($(this).data('fields').replace(regexp, time));
    return e.preventDefault();
  })
</script>

app/views/properties/_station_fields.html.erb
<div style="margin-bottom: 1rem;">
    <div class="field">
        <%= s.label :no %>
        <%= s.text_field :no %>
    </div>

    <div class="field">  
        <%= s.label :name %>
        <%= s.text_field :name %>
    </div>

    <div class="field">
        <%= s.label :railway_name %>
        <%= s.text_field :railway_name %>
    </div>

    <div class="field">
        <%= s.label :min_to_walk %>
        <%= s.text_field :min_to_walk %>
    </div>

    <%= s.hidden_field :_destroy %>
    <%= link_to "Remove", "#", class: "remove_fields" %>
</div>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rent fee</th>
      <th>Address</th>
      <th>Build year</th>
      <th>Remark</th>
      <th>Near Station</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.rent_fee %></td>
        <td><%= property.address %></td>
        <td><%= property.build_year %></td>
        <td><%= property.remark %></td>
        <td><%= property.stations.count %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @property.name %>
</p>

<p>
  <strong>Rent fee:</strong>
  <%= @property.rent_fee %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Build year:</strong>
  <%= @property.build_year %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @property.remark %>
</p>

<p>
  <% if @property.stations.count > 0 %>
  <strong>Near <%= pluralize(@property.stations.count, "Station") %></strong>
  <% end %>
</p>

<p>
  <% @property.stations.each do |s| %>
    <b><i>Station <%= s.no %></i></b>
    <p><%= s.name %></p>
    <p><%= s.railway_name %></p>
    <p><%= s.min_to_walk %></p>
  <% end %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/stations/_form.html.erb
<%= form_with(model: station, local: true) do |form| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :no %>
    <%= form.text_field :no %>
  </div>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :railway_name %>
    <%= form.text_field :railway_name %>
  </div>

  <div class="field">
    <%= form.label :min_to_walk %>
    <%= form.number_field :min_to_walk %>
  </div>

  <div class="field">
    <%= form.label :property_id %>
    <%= form.text_field :property_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stations</h1>

<table>
  <thead>
    <tr>
      <th>No</th>
      <th>Name</th>
      <th>Name</th>
      <th>Railway name</th>
      <th>Min to walk</th>
      <th>Property</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.no %></td>
        <td><%= station.name %></td>
        <td><%= station.railway_name %></td>
        <td><%= station.min_to_walk %></td>
        <td><%= station.property %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>No:</strong>
  <%= @station.no %>
</p>

<p>
  <strong>Name:</strong>
  <%= @station.name %>
</p>


<p>
  <strong>Railway name:</strong>
  <%= @station.railway_name %>
</p>

<p>
  <strong>Min to walk:</strong>
  <%= @station.min_to_walk %>
</p>

<p>
  <strong>Property:</strong>
  <%= @station.property %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>